//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BulkPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select ähnelt.
        /// </summary>
        internal static string CellButtonSelect {
            get {
                return ResourceManager.GetString("CellButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The configuration file could not be loaded. ähnelt.
        /// </summary>
        internal static string ExceptionConfigurationFileIsCorrupted {
            get {
                return ResourceManager.GetString("ExceptionConfigurationFileIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die One or more PDF files with the selected name already exists and is use by another application. Please close the other application and restart the creation process. ähnelt.
        /// </summary>
        internal static string ExceptionPDFFileAlreadyExistsAndInUse {
            get {
                return ResourceManager.GetString("ExceptionPDFFileAlreadyExistsAndInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die PDF file is corrupted. [{0}] ähnelt.
        /// </summary>
        internal static string ExceptionPDFIsCorrupted {
            get {
                return ResourceManager.GetString("ExceptionPDFIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The spreadsheet is in use by another application. Please close the other application and reselect the spreadsheet. ähnelt.
        /// </summary>
        internal static string ExceptionSpreadsheetAlreadyInUse {
            get {
                return ResourceManager.GetString("ExceptionSpreadsheetAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spreadsheet file is corrupted. ähnelt.
        /// </summary>
        internal static string ExceptionSpreadsheetIsCorrupted {
            get {
                return ResourceManager.GetString("ExceptionSpreadsheetIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aborted. ähnelt.
        /// </summary>
        internal static string MessageAborted {
            get {
                return ResourceManager.GetString("MessageAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Are you sure? ähnelt.
        /// </summary>
        internal static string MessageAreYouSure {
            get {
                return ResourceManager.GetString("MessageAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create {0} PDF files in {1}? ähnelt.
        /// </summary>
        internal static string MessageCreateNPDFFilesInDir {
            get {
                return ResourceManager.GetString("MessageCreateNPDFFilesInDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The filenames are not unique. ähnelt.
        /// </summary>
        internal static string MessageFilenameNotUnique {
            get {
                return ResourceManager.GetString("MessageFilenameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished. ähnelt.
        /// </summary>
        internal static string MessageFinished {
            get {
                return ResourceManager.GetString("MessageFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a output directory. ähnelt.
        /// </summary>
        internal static string MessageNoOutputDirSelected {
            get {
                return ResourceManager.GetString("MessageNoOutputDirSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a pdf file to continue. ähnelt.
        /// </summary>
        internal static string MessageNoPDFSelected {
            get {
                return ResourceManager.GetString("MessageNoPDFSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No usable rows was founded in this spreadsheet. ähnelt.
        /// </summary>
        internal static string MessageNoUsableRows {
            get {
                return ResourceManager.GetString("MessageNoUsableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected output directory does not exist. ähnelt.
        /// </summary>
        internal static string MessageOutputDirNotExist {
            get {
                return ResourceManager.GetString("MessageOutputDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a configuration file. ähnelt.
        /// </summary>
        internal static string MessageSelectConfiguration {
            get {
                return ResourceManager.GetString("MessageSelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a spreadsheet file to continue. ähnelt.
        /// </summary>
        internal static string MessageSelectSpreadsheet {
            get {
                return ResourceManager.GetString("MessageSelectSpreadsheet", resourceCulture);
            }
        }
    }
}
