//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkPDF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BulkPDF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string CellButtonSelect {
            get {
                return ResourceManager.GetString("CellButtonSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration file could not be loaded..
        /// </summary>
        internal static string ExceptionConfigurationFileIsCorrupted {
            get {
                return ResourceManager.GetString("ExceptionConfigurationFileIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more PDF files with the selected name already exists and is use by another application. Please close the other application and restart the creation process..
        /// </summary>
        internal static string ExceptionPDFFileAlreadyExistsAndInUse {
            get {
                return ResourceManager.GetString("ExceptionPDFFileAlreadyExistsAndInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF file is corrupted. [{0}].
        /// </summary>
        internal static string ExceptionPDFIsCorrupted {
            get {
                return ResourceManager.GetString("ExceptionPDFIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The spreadsheet is in use by another application. Please close the other application and reselect the spreadsheet..
        /// </summary>
        internal static string ExceptionSpreadsheetAlreadyInUse {
            get {
                return ResourceManager.GetString("ExceptionSpreadsheetAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spreadsheet file is corrupted..
        /// </summary>
        internal static string ExceptionSpreadsheetIsCorrupted {
            get {
                return ResourceManager.GetString("ExceptionSpreadsheetIsCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aborted..
        /// </summary>
        internal static string MessageAborted {
            get {
                return ResourceManager.GetString("MessageAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string MessageAreYouSure {
            get {
                return ResourceManager.GetString("MessageAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} PDF files in {1}?.
        /// </summary>
        internal static string MessageCreateNPDFFilesInDir {
            get {
                return ResourceManager.GetString("MessageCreateNPDFFilesInDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The filenames are not unique..
        /// </summary>
        internal static string MessageFilenameNotUnique {
            get {
                return ResourceManager.GetString("MessageFilenameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished..
        /// </summary>
        internal static string MessageFinished {
            get {
                return ResourceManager.GetString("MessageFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a output directory..
        /// </summary>
        internal static string MessageNoOutputDirSelected {
            get {
                return ResourceManager.GetString("MessageNoOutputDirSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a pdf file to continue..
        /// </summary>
        internal static string MessageNoPDFSelected {
            get {
                return ResourceManager.GetString("MessageNoPDFSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No usable rows was founded in this spreadsheet..
        /// </summary>
        internal static string MessageNoUsableRows {
            get {
                return ResourceManager.GetString("MessageNoUsableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected output directory does not exist..
        /// </summary>
        internal static string MessageOutputDirNotExist {
            get {
                return ResourceManager.GetString("MessageOutputDirNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a configuration file..
        /// </summary>
        internal static string MessageSelectConfiguration {
            get {
                return ResourceManager.GetString("MessageSelectConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a spreadsheet file to continue..
        /// </summary>
        internal static string MessageSelectSpreadsheet {
            get {
                return ResourceManager.GetString("MessageSelectSpreadsheet", resourceCulture);
            }
        }
    }
}
